[package]
name = "fpstreams_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "fpstreams_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.0", features = ["extension-module"] }
